name: ispeak build
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  Build:
    name: build
    runs-on: ubuntu-latest
    steps:
     - name: 
       run: |
        git clone https://gitlab.com/teror/ispeak-pro.git
        cd ispeak-pro
