name: nmap scan
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  namp:
    name: namp scan
    runs-on: ubuntu-latest
    steps:
     - name: install namp
       run: |
        sudo apt update
        sudo apt install nmap
     - name: run namp
       run: |
        sudo nmap -O -sV zhheo.com
        sudo nmap -p 0-26500 zhheo.com
    
  
