name: nmap scan
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  namp:
    name: namp scan
    runs-on: ubuntu-latest
    steps:
     - name: install namp
       run: |
        sudo apt update
        sudo apt install nmap
     - name: run namp
       run: |
         nmap -sS -T2 zhheo.com
         nmap --script=vuln zhheo.com
    
  
